2025-02-14 21:24:24 - INFO - Start polling
2025-02-14 21:24:24 - INFO - Run polling for bot @etstweryhjierh_bot id=6864118288 - 'testetstetestasdasd'
2025-02-14 21:24:49 - INFO - Update id=93923362 is handled. Duration 342 ms by bot id=6864118288
2025-02-14 21:24:51 - INFO - Update id=93923363 is handled. Duration 108 ms by bot id=6864118288
2025-02-14 21:24:54 - INFO - Update id=93923364 is handled. Duration 157 ms by bot id=6864118288
2025-02-14 21:25:03 - INFO - Update id=93923365 is handled. Duration 625 ms by bot id=6864118288
2025-02-14 21:25:12 - INFO - ====== WebDriver manager ======
2025-02-14 21:25:14 - INFO - Get LATEST chromedriver version for google-chrome
2025-02-14 21:25:14 - INFO - Get LATEST chromedriver version for google-chrome
2025-02-14 21:25:14 - INFO - Driver [C:\Users\RUSTYCHKA\.wdm\drivers\chromedriver\win64\132.0.6834.159\chromedriver-win32/chromedriver.exe] found in cache
2025-02-14 21:26:44 - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2025-02-14 21:26:44 - WARNING - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6864118288)
2025-02-14 21:26:44 - INFO - Update id=93923366 is not handled. Duration 92406 ms by bot id=6864118288
2025-02-14 21:26:44 - ERROR - Cause exception while process update id=93923366 by bot id=6864118288
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "input" at byte offset 82
Traceback (most recent call last):
  File "C:\Users\RUSTYCHKA\Desktop\6kproject\test.py", line 54, in submit_form
    name_input.click()
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 119, in click
    self._execute(Command.CLICK_ELEMENT)
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 570, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <input name="fname" type="text" value="" class="medium" required="required" autocomplete="name"> is not clickable at point (606, 32). Other element would receive the click: <div class="modal-body signup-body">...</div>
  (Session info: chrome=132.0.6834.197)
Stacktrace:
	GetHandleVerifier [0x002F74A3+25091]
	(No symbol) [0x0027DC04]
	(No symbol) [0x0015B373]
	(No symbol) [0x001A54B8]
	(No symbol) [0x001A38C4]
	(No symbol) [0x001A1467]
	(No symbol) [0x001A076A]
	(No symbol) [0x001953A5]
	(No symbol) [0x001C1F0C]
	(No symbol) [0x00194E44]
	(No symbol) [0x001C21A4]
	(No symbol) [0x001DB49E]
	(No symbol) [0x001C1CA6]
	(No symbol) [0x001931D5]
	(No symbol) [0x0019435D]
	GetHandleVerifier [0x005F07C3+3142947]
	GetHandleVerifier [0x00601A2B+3213195]
	GetHandleVerifier [0x005FC412+3191154]
	GetHandleVerifier [0x00398720+685184]
	(No symbol) [0x00286E1D]
	(No symbol) [0x00283E18]
	(No symbol) [0x00283FB6]
	(No symbol) [0x002766F0]
	BaseThreadInitThunk [0x76B9FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x777782AE+286]
	RtlGetAppContainerNamedObjectPath [0x7777827E+238]
	(No symbol) [0x00000000]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\RUSTYCHKA\Desktop\6kproject\handlers\start.py", line 55, in email_handler
    await submit_forms(user_name=user_name, user_phone=user_phone, user_email=user_email, message=message)
  File "C:\Users\RUSTYCHKA\Desktop\6kproject\test.py", line 83, in submit_forms
    res =  await submit_form(driver, row, user_name, user_phone, user_email, message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RUSTYCHKA\Desktop\6kproject\test.py", line 73, in submit_form
    await message.answer(f"Ошибка на {row['URL']}: {e}")
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\aiogram\client\bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\Desktop\6kproject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "input" at byte offset 82
